import os
from fpdf import FPDF
from datetime import datetime
from pathlib import Path


class CoverLetterPDF(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by Job Copilot — {datetime.now().strftime('%B %d, %Y')}", align="C")


def generate_cover_letter_pdf(
    candidate_name: str,
    candidate_email: str,
    job_title: str,
    company: str,
    cover_letter_text: str,
    output_path: str,
) -> str:
    pdf = CoverLetterPDF()
    pdf.add_page()
    pdf.set_margins(25, 25, 25)
    pdf.set_auto_page_break(auto=True, margin=20)

    # Header — candidate info
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, candidate_name, ln=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5, candidate_email, ln=True)
    pdf.ln(6)

    # Date
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, datetime.now().strftime("%B %d, %Y"), ln=True)
    pdf.ln(4)

    # Role + company
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 6, f"Re: {job_title}", ln=True)
    pdf.cell(0, 6, company, ln=True)
    pdf.ln(8)

    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.line(25, pdf.get_y(), 185, pdf.get_y())
    pdf.ln(8)

    # Cover letter body
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(40, 40, 40)

    for paragraph in cover_letter_text.split("\n\n"):
        paragraph = paragraph.strip()
        if paragraph:
            pdf.multi_cell(0, 6, paragraph)
            pdf.ln(4)

    pdf.output(output_path)
    return output_path


def generate_fit_pdf(
    candidate_name: str,
    job_title: str,
    company: str,
    match_score: float,
    faithfulness_score: float,
    quality_score: float,
    fit_analysis: dict,
    cover_letter_text: str,
    verdicts: list,
    output_path: str,
) -> str:
    pdf = CoverLetterPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)

    def section_header(title: str):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_fill_color(245, 245, 245)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, title, ln=True, fill=True)
        pdf.ln(3)

    def body_text(text: str):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 5, text)
        pdf.ln(2)

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 10, "Application Fit Report", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"{job_title} at {company}", ln=True)
    pdf.cell(0, 6, f"Candidate: {candidate_name}", ln=True)
    pdf.cell(0, 6, datetime.now().strftime("%B %d, %Y"), ln=True)
    pdf.ln(8)

    # Scores
    section_header("Match Scores")
    scores = [
        ("Overall Match Score", f"{match_score:.0%}"),
        ("Faithfulness Score", f"{faithfulness_score:.0%}" if faithfulness_score else "N/A"),
        ("Quality Score", f"{quality_score:.0%}" if quality_score else "N/A"),
    ]
    for label, value in scores:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(80, 6, label)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 6, value, ln=True)
    pdf.ln(6)

    # Fit analysis
    if fit_analysis:
        section_header("Where You Fit")
        strong_matches = fit_analysis.get("strong_matches", [])
        for match in strong_matches[:6]:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 5, f"✓ {match.get('requirement', '')[:80]}", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 5, f"  Evidence: {match.get('evidence', '')[:120]}")
            pdf.ln(2)

        gaps = fit_analysis.get("gaps", [])
        if gaps:
            pdf.ln(4)
            section_header("Gaps to Address")
            for gap in gaps[:4]:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(30, 30, 30)
                pdf.cell(0, 5, f"△ {gap.get('requirement', '')[:80]}", ln=True)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 5, f"  Mitigation: {gap.get('mitigation', '')[:120]}")
                pdf.ln(2)

    # Faithfulness verdicts
    if verdicts:
        pdf.add_page()
        section_header("Claim Verification (Faithfulness Check)")
        for v in verdicts:
            icon = "✓" if v.get("verdict") == "SUPPORTED" else "✗"
            pdf.set_font("Helvetica", "", 9)
            color = (40, 120, 40) if v.get("verdict") == "SUPPORTED" else (180, 40, 40)
            pdf.set_text_color(*color)
            pdf.multi_cell(0, 5, f"{icon} {v.get('claim', '')[:100]}")
        pdf.ln(4)

    # Cover letter
    pdf.add_page()
    section_header("Cover Letter")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    for paragraph in cover_letter_text.split("\n\n"):
        paragraph = paragraph.strip()
        if paragraph:
            pdf.multi_cell(0, 6, paragraph)
            pdf.ln(4)

    pdf.output(output_path)
    return output_path